#:import ControlPanel seqer.uix.control_panel.ControlPanel
#:import BPMGauge seqer.uix.bpm_gauge.BPMGauge
#:import QuantizerPanel seqer.uix.quantizer_panel.QuantizerPanel


<Label>:
    color: 0.8, 0.8, 0.8, 1.0

BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.05

        ControlPanel:
        BPMGauge:
        QuantizerPanel:

    Button:
        size_hint_y: 0.95
